apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.yaml
  - rbac/role-binding.yaml
  - cert-manager-tls.yaml

configMapGenerator:
  - name: grafana-dashboards-custom
    files:
      - dashboards/14361_rev1.json
      - dashboards/alb-traffic.json
      - dashboards/k8s-core-metrics.json
      - dashboards/karpenter-metrics.json
    options:
      labels:
        grafana_dashboard: "1"

  - name: prometheus-rules-custom
    files:
      - rules/alarm-pipeline.yaml
    options:
      labels:
        prometheus_rule: "1"

  - name: alertmanager-templates
    files:
      - alertmanager/chatops-top3.tmpl
