apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service
  namespace: store-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
        security.localy.io/zero-trust: "enforced"
    spec:
      serviceAccountName: store-service-sa
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: store-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: app
          image: localy/store-service:latest
          ports:
            - containerPort: 8071
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configtree:/mnt/secrets/app-creds/,optional:configtree:/mnt/config/"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop: ["ALL"]
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 25"]
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
