apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  # Must match L2 IAM role: ${cluster_name}-karpenter-node-role
  role: "prod-eks-karpenter-node-role"
  subnetSelectorTerms:
    - tags:
        # Must match EKS/VPC subnet tags from Terraform
        karpenter.sh/discovery: prod-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: prod-eks
  metadataOptions:
    httpTokens: required
    httpPutResponseHopLimit: 1
    httpEndpoint: enabled
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
  tags:
    Environment: "prod"
    ManagedBy: "karpenter"
    localy.io/cost-center: "shared"
    localy.io/finops: "enabled"
