# Keep in sync with SSM /localy/prod/network/vpc_id and cluster name after redeploy.
clusterName: "prod-eks"
region: "ap-northeast-2"
vpcId: "vpc-0adb5b65547670768"

serviceAccount:
  create: true
  name: "aws-load-balancer-controller"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::533003975005:role/AWSLoadBalancerControllerIAMRole-prod"

serviceMonitor:
  enabled: false
