apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: payment-service
data:
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "AWS_MSK_IAM"
  KAFKA_SASL_JAAS_CONFIG: "software.amazon.msk.auth.iam.IAMLoginModule required;"
  KAFKA_SASL_CALLBACK_HANDLER: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
