apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: payment-service
data:
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "AWS_MSK_IAM"
  KAFKA_SASL_JAAS_CONFIG: "software.amazon.msk.auth.iam.IAMLoginModule required;"
  KAFKA_SASL_CALLBACK_HANDLER: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
  # Force ALL Kafka clients (binder consumers/producers/retry) onto MSK IAM
  SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: "SASL_SSL"
  SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: "AWS_MSK_IAM"
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: "software.amazon.msk.auth.iam.IAMLoginModule required;"
  SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SECURITY_PROTOCOL: "SASL_SSL"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SASL_MECHANISM: "AWS_MSK_IAM"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SASL_JAAS_CONFIG: "software.amazon.msk.auth.iam.IAMLoginModule required;"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SASL_CLIENT_CALLBACK_HANDLER_CLASS: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_CONSUMER_PROPERTIES_SECURITY_PROTOCOL: "SASL_SSL"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_CONSUMER_PROPERTIES_SASL_MECHANISM: "AWS_MSK_IAM"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_CONSUMER_PROPERTIES_SASL_JAAS_CONFIG: "software.amazon.msk.auth.iam.IAMLoginModule required;"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_CONSUMER_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_PRODUCER_PROPERTIES_SECURITY_PROTOCOL: "SASL_SSL"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_PRODUCER_PROPERTIES_SASL_MECHANISM: "AWS_MSK_IAM"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_PRODUCER_PROPERTIES_SASL_JAAS_CONFIG: "software.amazon.msk.auth.iam.IAMLoginModule required;"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_PRODUCER_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
