apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment-service
spec:
  template:
    spec:
      containers:
        - name: payment-service
          envFrom:
            - configMapRef:
                name: payment-service-config
          volumeMounts:
            - name: secret-volume
              mountPath: /workspace/configtree
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: payment-service-secret
