apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-service-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: payment-service-secret
    creationPolicy: Owner
    template:
      data:
        SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .database }}"
        SPRING_DATASOURCE_USERNAME: "{{ .username }}"
        SPRING_DATASOURCE_PASSWORD: "{{ .password }}"
  data:
    - secretKey: host
      remoteRef:
        key: localy-prod-database-credentials
        property: host
    - secretKey: port
      remoteRef:
        key: localy-prod-database-credentials
        property: port
    - secretKey: database
      remoteRef:
        key: localy-prod-database-credentials
        property: database
    - secretKey: username
      remoteRef:
        key: localy-prod-database-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: localy-prod-database-credentials
        property: password
