apiVersion: v1
kind: LimitRange
metadata:
  name: payment-service-limit-range
  namespace: payment-service
  annotations:
    localy.io/phase: "5"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      default:
        cpu: 500m
        memory: 1Gi
      max:
        cpu: "2000m"
        memory: 2Gi
      min:
        cpu: 50m
        memory: 64Mi
---
# 1500m × 10 × 1.15 ≈ 17.25 → ceil 18 CPU / 2Gi × 10 × 1.15 ≈ 23Gi
apiVersion: v1
kind: ResourceQuota
metadata:
  name: payment-service-quota
  namespace: payment-service
  annotations:
    localy.io/phase: "5"
spec:
  hard:
    pods: "12"
    requests.cpu: "4"
    requests.memory: "12Gi"
    limits.cpu: "18"
    limits.memory: "24Gi"
