apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: edge-service
          envFrom:
            - configMapRef:
                name: edge-service-config
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 15"]
