apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: edge-service-pdb
  namespace: edge-service
  annotations:
    localy.io/phase: "5"
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: edge-service
