apiVersion: v1
kind: LimitRange
metadata:
  name: edge-service-limit-range
  namespace: edge-service
  annotations:
    localy.io/phase: "5"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      default:
        cpu: 500m
        memory: 1Gi
      max:
        cpu: "2000m"
        memory: 2Gi
      min:
        cpu: 50m
        memory: 64Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: edge-service-quota
  namespace: edge-service
  annotations:
    localy.io/phase: "5"
spec:
  hard:
    pods: "12"
    requests.cpu: "3"
    requests.memory: "8Gi"
    limits.cpu: "12"
    limits.memory: "16Gi"
