apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pod-disruption-budget.yaml
  - service-monitor.yaml
  - ../../base
  - scaled-object.yaml
  - network-policy.yaml
  - configmap.yaml
  - service-account.yaml
  - secret-store.yaml
  - external-secret.yaml

images:
  - name: localy-order-service
    newName: 533003975005.dkr.ecr.ap-northeast-2.amazonaws.com/order-service
    newTag: e2e1
