apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: auth-namespace
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: keycloak-store
    kind: SecretStore
  target:
    name: localy-keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: localy-prod-keycloak-admin
        property: username
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: localy-prod-keycloak-admin
        property: password
    - secretKey: KEYCLOAK_DATABASE_PASSWORD
      remoteRef:
        key: localy-prod-database-credentials
        property: password
    - secretKey: KEYCLOAK_DATABASE_HOST
      remoteRef:
        key: localy-prod-database-credentials
        property: host
