apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak-store
  namespace: auth-namespace
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
