apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak-store
  namespace: auth-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
