apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alb-controller.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - fluent-bit.yaml
  - ingress-core.yaml
  - karpenter-controller.yaml
  - karpenter-provisioner.yaml
  - kube-prometheus-stack.yaml
  - kyverno.yaml
  - loki.yaml
  - node-local-dns.yaml
  - storage.yaml
  - user-service.yaml
  - payment-service.yaml
  - store-service.yaml
