apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-db-secrets
  namespace: payment-service
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    localy.io/phase: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: SecretStore
  target:
    name: payment-service-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        spring.datasource.url: "jdbc:postgresql://{{ .host }}:{{ .port }}/paymentdb?sslmode=require"
        spring.datasource.username: "{{ .username }}"
        spring.datasource.password: "{{ .password }}"
        spring.kafka.bootstrap-servers: "{{ .msk }}"
  data:
    - secretKey: host
      remoteRef:
        key: /localy/prod/workload/payment-db
        property: host
    - secretKey: port
      remoteRef:
        key: /localy/prod/workload/payment-db
        property: port
    - secretKey: username
      remoteRef:
        key: /localy/prod/workload/payment-db
        property: username
    - secretKey: password
      remoteRef:
        key: /localy/prod/workload/payment-db
        property: password
    - secretKey: msk
      remoteRef:
        key: /localy/prod/workload/payment-db
        property: msk_bootstrap_servers
