apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service-sa
  namespace: payment-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::533003975005:role/prod-eks-payment-service-irsa-role
