apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: platform-secret-store
  namespace: edge-service
  annotations:
    localy.io/phase: "7-correction"
    localy.io/allowed-sm-path: "/localy/prod/workload/edge-*"
    localy.io/irsa-role: "prod-eks-edge-service-irsa-role"
    localy.io/domain-alias: "gateway-service"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: edge-service-sa
