apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-service-sa
  namespace: edge-service
  annotations:
    localy.io/phase: "4"
    eks.amazonaws.com/role-arn: arn:aws:iam::533003975005:role/prod-eks-edge-service-irsa-role
