apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: karpenter
    repo: public.ecr.aws/karpenter
    version: 0.37.0
    releaseName: karpenter
    namespace: kube-system
    includeCRDs: true
