# ESO sync: SSM ACM/WAF ARNs → kube-system Secret (Stage 2 of ESO+inject)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-ingress-aws-ids
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Delete=false,Prune=false
    localy.io/phase: "eso-inject-s2"
spec:
  project: platform-project
  source:
    repoURL: "https://github.com/hetrkumt/localy-manifests.git"
    path: apps/alb-ingress-aws-ids
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Delete=false
      - Prune=false
