provider: "aws"
source: "ingress"
policy: "upsert-only"
txtOwnerId: "prod-platform-eks"

domainFilters:
  - "feifo.click"

metrics:
  enabled: true
serviceMonitor:
  enabled: false

serviceAccount:
  create: true
  name: "external-dns-sa"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::533003975005:role/prod-externaldns-irsa-role"
