provider: "aws"
source: "ingress"
policy: "upsert-only"
txtOwnerId: "prod-platform-eks"

domainFilters:
  - "feifo.click"

metrics:
  enabled: true
serviceMonitor:
  enabled: false

serviceAccount:
  create: true
  name: "external-dns-sa"
  annotations:
    eks.amazonaws.com/role-arn: "<PLACEHOLDER_EXTERNAL_DNS_IAM_ROLE_ARN>"
