apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-platform-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:ap-northeast-2:533003975005:regional/webacl/prod-ingress-waf/22369cc2-004f-4469-9197-1f010fec52f5"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:533003975005:certificate/75828507-ed10-4d01-a69c-29cf39f6cc85"
