apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-platform-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:ap-northeast-2:533003975005:regional/webacl/prod-ingress-waf/a5da2535-03bf-424c-9d52-82f152c9047d"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:533003975005:certificate/9c6d9adb-1dae-453d-bd05-2574a93820de"
