apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-service-sa
  namespace: store-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::533003975005:role/prod-eks-store-service-irsa-role
