apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: 21.4.2
    releaseName: keycloak
    namespace: auth-namespace
    valuesFile: values.yaml

configMapGenerator:
  - name: keycloak-realm-config
    namespace: auth-namespace
    files:
      - realm-import.json
