apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product-store-db-secrets
  namespace: store-service
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    localy.io/phase: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: SecretStore
  target:
    name: localy-store-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        spring.r2dbc.username: "{{ .username }}"
        spring.r2dbc.password: "{{ .password }}"
        aws.s3.bucket-name: "{{ .bucket }}"
        aws.kms.key-arn: "{{ .kms }}"
  data:
    - secretKey: username
      remoteRef:
        key: /localy/prod/workload/store-db
        property: username
    - secretKey: password
      remoteRef:
        key: /localy/prod/workload/store-db
        property: password
    - secretKey: bucket
      remoteRef:
        key: /localy/prod/workload/store-db
        property: s3_bucket_name
    - secretKey: kms
      remoteRef:
        key: /localy/prod/workload/store-db
        property: kms_key_arn
