apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: store-service-secrets
  namespace: store-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: store-service-store
    kind: SecretStore
  target:
    name: localy-store-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_R2DBC_USERNAME
      remoteRef:
        key: localy-prod-database-credentials
        property: username
    - secretKey: SPRING_R2DBC_PASSWORD
      remoteRef:
        key: localy-prod-database-credentials
        property: password
    - secretKey: AWS_S3_BUCKET_NAME
      remoteRef:
        key: /localy/prod/apps/s3/store_bucket_name
    - secretKey: AWS_KMS_KEY_ARN
      remoteRef:
        key: /localy/prod/apps/kms/store_key_arn
    - secretKey: AWS_POD_ROLE_ARN
      remoteRef:
        key: /localy/prod/apps/iam/store_role_arn
