apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: store-service
bases:
  - ../../base
resources:
  - external-secret.yaml
  - service-account.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
  - secret-store.yaml
