apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: store-service
bases:
  - ../../base
resources:
  - secret-store.yaml
  - external-secret.yaml
  - service-account.yaml
patchesStrategicMerge:
  - deployment-patch.yaml


images:
  - name: localy/store-service
    newName: 533003975005.dkr.ecr.ap-northeast-2.amazonaws.com/store-service
    newTag: latest
