apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::533003975005:role/prod-store-service-pod-role"
  name: store-service-sa
  namespace: store-service
