apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: node-local-dns
    repo: https://kubernetes-sigs.github.io/node-local-dns/
    version: 0.1.3
    releaseName: node-local-dns
    namespace: kube-system
