apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: cart-service
spec:
  template:
    spec:
      readinessGates:
        - conditionType: target-health.elbv2.k8s.aws
      containers:
        - name: app
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
