apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cart-service-db-secrets
  namespace: cart-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cart-service-store
    kind: SecretStore
  target:
    name: localy-cart-db-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATA_REDIS_PASSWORD
      remoteRef:
        key: localy-prod-database-credentials
        property: password
