apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-service-hpa
  namespace: cart-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-service
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second # [핵심] Prometheus가 수집하는 커스텀 메트릭
        target:
          type: AverageValue
          averageValue: 100 # 파드 1개당 초당 100건의 HTTP 요청을 초과하면 즉각 스케일 아웃
