apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pod-disruption-budget.yaml
  - service-monitor.yaml
  - external-secret.yaml
  - secret-store.yaml
  - configmap.yaml
  - service-account.yaml
  - scaled-object.yaml
  - network-policy.yaml
  - resource-guards.yaml

images:
  - name: localy/cart-service
    newName: 533003975005.dkr.ecr.ap-northeast-2.amazonaws.com/cart-service
    newTag: e2e1

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
