resources:
  - pod-disruption-budget.yaml
  - service-monitor.yaml
  - ../../base
  - external-secret.yaml
  - secret-store.yaml
  - configmap.yaml
  - service-account.yaml
  - hpa.yaml # ?좉퇋 二쇱엯
  - network-policy.yaml # ?좉퇋 二쇱엯

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml

