apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cart-service-pdb
  namespace: cart-service
  annotations:
    localy.io/phase: "5"
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: cart-service
