apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart-service-sa
  namespace: cart-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::533003975005:role/prod-eks-workload-pod-identity-role
