apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-service-monitor
  namespace: cart-service
  labels:
    app: cart-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cart-service
  endpoints:
  - port: management
    path: /actuator/prometheus
    interval: 15s
