apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart-service-sa
  namespace: cart-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/localy-prod-cart-service-secrets-role
