apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cart-redis-secrets
  namespace: cart-service
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    localy.io/phase: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: SecretStore
  target:
    name: localy-cart-db-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        spring.data.redis.password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /localy/prod/workload/cart-redis
        property: password
