apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cart-service
resources:
  - service-account.yaml
  - secret-store.yaml
  - external-secret.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: cart-service
commonAnnotations:
  localy.io/phase: "7-correction"
  localy.io/zero-trust: "configtree"
