settings:
  clusterName: "prod-eks"
  clusterEndpoint: "https://E583CF0454E256924147D1439D485B87.gr7.ap-northeast-2.eks.amazonaws.com"
  interruptionQueue: "prod-eks-karpenter-interruption-queue"

serviceAccount:
  name: "karpenter"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::533003975005:role/prod-eks-karpenter-controller-role"

nodeSelector:
  role: "system"

serviceMonitor:
  enabled: true
  additionalLabels:
    release: "kube-prometheus-stack"
