apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.yaml
  - policies/kyverno-policy.yaml
  - policies/protect-alertmanager.yaml
  - policies/prevent-cross-namespace-secrets.yaml
  - policies/enforce-rollout-probes.yaml
  - policies/restrict-rollout-traffic-routing.yaml
