apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Helm Chart ?뚮뜑留?寃곌낵臾쇨낵 ?쒖닔 K8s 留ㅻ땲?섏뒪?몃뱾???섎굹濡?臾띠뼱以띾땲??
resources:
  - network-policy.yaml
  - policies/kyverno-policy.yaml
  - policies/protect-alertmanager.yaml
