apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kyverno-admission-ingress-zero-trust
  namespace: kyverno
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: network-policy
    managed-by: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # [è«›â‘¹ë¼??1] Control Plane ?ë±ì’ ??ë–Š
    - from:
        - ipBlock:
            cidr: 10.0.12.0/24,10.0.13.0/24,10.0.11.0/24
      ports:
        - protocol: TCP
          port: 9443
    # Kyverno ??€? ?ŒëŒ„ë£??°ë“ƒ åª????–Š ??‰ìŠœ
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: kyverno
      ports:
        - protocol: TCP
          port: 9443
  egress:
    # [è«›â‘¹ë¼??2] K8s API ??•ì¾­ ???–Š
    - to:
        - ipBlock:
            cidr: 10.100.0.1/32
      ports:
        - protocol: TCP
          port: 443
    # CoreDNS ??€ì«???????‰ìŠœ
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
