apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workload-dbs-rds-creds
  namespace: workload-dbs
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    localy.io/ssot: "terraform:localy-prod-database-credentials"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: workload-dbs-store
    kind: SecretStore
  target:
    name: workload-dbs-rds-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: workload-dbs
          app.kubernetes.io/component: rds-credentials
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
      data:
        host: "{{ .host }}"
        password: "{{ .password }}"
  data:
    - secretKey: host
      remoteRef:
        key: localy-prod-database-credentials
        property: host
    - secretKey: password
      remoteRef:
        key: localy-prod-database-credentials
        property: password
