apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: user-service
data:
  # TODO: 실제 Keycloak 주소로 변경 필요
  KEYCLOAK_BASE_URL: "http://keycloak.auth-namespace.svc.cluster.local:8080"
  KEYCLOAK_ISSUER_URI: "http://keycloak.auth-namespace.svc.cluster.local:8080/realms/localy"
