apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 45
      readinessGates:
        - conditionType: target-health.elbv2.k8s.aws
      containers:
        - name: app
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              memory: "512Mi"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
          envFrom:
            - secretRef:
                name: localy-user-keycloak-secret
