apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-service-keycloak-secrets
  namespace: user-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: user-service-store
    kind: SecretStore
  target:
    name: localy-user-keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: localy-prod-user-keycloak-credentials
        property: clientSecret
