apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: user-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/localy-prod-user-service-secrets-role
