apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: order-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::533003975005:role/prod-eks-order-service-irsa-role
