apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localy-external-alb-edge
  namespace: edge-service
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/group.name: "localy-external-alb"
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:533003975005:certificate/75828507-ed10-4d01-a69c-29cf39f6cc85"
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:ap-northeast-2:533003975005:regional/webacl/prod-ingress-waf/22369cc2-004f-4469-9197-1f010fec52f5"
    external-dns.alpha.kubernetes.io/hostname: "feifo.click"
spec:
  rules:
    - host: "feifo.click"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: "edge-service"
                port:
                  number: 80
